# Pandas  

Pandas is a popular open-source data analysis and manipulation library for Python. Pandas stands for “Python Data Analysis Library ”. The name is derived from the term “panel data”, an econometrics term for multidimensional structured data sets. It provides easy-to-use and powerful tools for working with structured data such as tables and time series.

Some advantages of Pandas include:

* Data manipulation: Pandas provides powerful tools for filtering, transforming, and aggregating data.
* Flexibility: Pandas can handle a wide range of data formats, including text files, CSV, Excel, SQL databases, and JSON.
* Integration with other libraries: Pandas works seamlessly with other data science libraries in Python, such as NumPy and Matplotlib.
* Time series analysis: Pandas has built-in support for working with time series data.

Also:

* Highly optimized for performance, with critical code paths written in Cython or C.

In [1]:
import pandas as pd # import pandas library, and use pd as alias (this is a convention)

## Data Structures

Pandas data structures include Series and DataFrames.
* A Series is a one-dimensional array-like object that can hold a variety of data types, such as integers, strings, and floats.
* A DataFrame is a two-dimensional table-like data structure with rows and columns.

### Series
A Pandas Series is a one-dimensional labeled array that can hold any data type such as integers, floating-point numbers, strings, Python objects, etc. Each element in a Series has a label called the index, which is used to access the values of the Series. A Series is similar to a NumPy array, but it has an index that makes it more flexible and convenient to use.

In [2]:
# create a Series from a list
s1 = pd.Series([3, 5, 1, 2, 7])
print(s1)

0    3
1    5
2    1
3    2
4    7
dtype: int64

In [3]:
# create a Series from a dictionary
data = {'apples': 5, 'oranges': 2, 'bananas': 8, 'pears': 1}
s2 = pd.Series(data)
print(s2)

apples     5
oranges    2
bananas    8
pears      1
dtype: int64

In [4]:
# create a Series with custom index labels
s3 = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print(s3)

a    10
b    20
c    30
d    40
dtype: int64

In [5]:
# access elements of a Series using index labels
print(s2['apples'])   # output: 5
print(s3[['a', 'c']]) # output: a    10, c    30

5
a    10
c    30
dtype: int64

In [6]:
# perform arithmetic operations on Series
s4 = s1 + s1
print(s4)

0     6
1    10
2     2
3     4
4    14
dtype: int64

In [7]:
# create a boolean mask from a Series
mask = s1 > 3
print(mask)

0    False
1     True
2    False
3    False
4     True
dtype: bool

In [8]:
# filter a Series using a boolean mask
filtered_s1 = s1[mask]
print(filtered_s1)

1    5
4    7
dtype: int64

In [9]:
# apply a function to each element of a Series
s5 = s1.apply(lambda x: x ** 2)
print(s5)

0     9
1    25
2     1
3     4
4    49
dtype: int64

### DataFrame  
A Pandas DataFrame is a two-dimensional labeled data structure that is used to store and manipulate tabular data. It consists of rows and columns, where each column can have a different data type. A DataFrame can be thought of as a collection of Series that share the same index. The rows are labeled by the index, and the columns are labeled by their names. DataFrame is the most commonly used Pandas data structure and can be thought of as a spreadsheet or SQL table. It provides powerful data manipulation and analysis functionalities, such as data indexing, selection, merging, grouping, and pivoting.

In [10]:
# create a DataFrame from a dictionary
data = {'name': ['Alice', 'Bob', 'Charlie', 'Dave'],
        'age': [25, 30, 35, 40],
        'country': ['USA', 'Canada', 'Australia', 'UK']}

df = pd.DataFrame(data)
print(df)

      name  age    country
0    Alice   25        USA
1      Bob   30     Canada
2  Charlie   35  Australia
3     Dave   40         UK

In [14]:
# create a DataFrame from a CSV file
df = pd.read_csv('/content/sample_data/california_housing_train.csv')
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

In [16]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [ ]:
# create a DataFrame from a NumPy array
import numpy as np

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
columns = ['A', 'B', 'C']

df = pd.DataFrame(data, columns=columns)
print(df)

In [ ]:
# create a DataFrame from a list of dictionaries
data = [{'name': 'Alice', 'age': 25, 'country': 'USA'},
        {'name': 'Bob', 'age': 30, 'country': 'Canada'},
        {'name': 'Charlie', 'age': 35, 'country': 'Australia'},
        {'name': 'Dave', 'age': 40, 'country': 'UK'}]

df = pd.DataFrame(data)
print(df)

In [ ]:
# load a JSON file into a DataFrame
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/data.json'

# Load the first sheet of the JSON file into a data frame​
df = pd.read_json(url, orient='columns')
print(df.head())

Data indexing and selection is a crucial aspect of data analysis. Pandas provides flexible ways to select subsets of data using methods such as loc and iloc.


Here are some common methods of the Pandas DataFrame:

* `head()`: Returns the first n rows of the DataFrame. The default value of n is 5.
* `tail()`: Returns the last n rows of the DataFrame. The default value of n is 5.
* `info()`: Prints a summary of the DataFrame, including the column names, data types, and non-null values.
* `describe()`: Generates descriptive statistics for numerical columns in the DataFrame, such as count, mean, and standard deviation.
* `shape`: Returns a tuple representing the dimensions of the DataFrame, i.e., (number of rows, number of columns).
* `columns`: Returns a list of the column names in the DataFrame.
* `index`: Returns a list of the row labels or index values in the DataFrame.
* `loc[]`: Allows you to access a group of rows and columns in the DataFrame using label-based indexing. For example, `df.loc[0:5, ['Name', 'Age']]` returns the rows from index 0 to 5, and the "Name" and "Age" columns.
* `iloc[]`: Allows you to access a group of rows and columns in the DataFrame using integer-based indexing. For example `df.iloc[0:5, [0, 1]]` returns the first 5 rows and the first 2 columns.
* `drop()`: Removes one or more rows or columns from the DataFrame. For example, df.drop('Age', axis=1) removes the "Age" column.
* `fillna()`: Fills missing or NaN (Not a Number) values in the DataFrame with a specified value or method, such as the mean or median.
* `groupby()`: Groups the DataFrame by one or more columns and applies a function, such as mean or sum, to each group.
* `pivot_table()`: Creates a pivot table from the DataFrame, allowing you to summarize and analyze the data in different* ways.
* `merge()`: Merges two or more DataFrames based on a common column or index.
* `sort_values()`: Sorts the DataFrame by one or more columns in ascending or descending order.
* `to_csv()`: Writes the DataFrame to a CSV file.
* `plot()`: Creates a basic plot of the DataFrame, such as a line chart or histogram.

These are just a few of the many methods available in Pandas DataFrame. Pandas offers a rich set of functions for data manipulation, aggregation, and visualization, making it a powerful tool for data analysis.

## Indexing, .loc[], and .iloc[]

Pandas provides different methods to select rows and columns of data, the most important of which are loc and iloc. Understanding the differences between these methods is crucial for data manipulation in pandas.

## Indexing

An `index` in pandas is like an address, that’s how any data point across the dataframe or series can be accessed. Rows and columns both have indexes, rows indices are called as index and for columns its general column names.

In [54]:
data = {
    'age': [30, 2, 12, 4, 32, 33, 69],
    'color': ['blue', 'green', 'red', 'white', 'gray', 'black', 'red'],
    'food': ['Steak', 'Lamb', 'Mango', 'Apple', 'Cheese', 'Melon', 'Beans'],
    'height': [165, 70, 120, 80, 180, 172, 150],
    'score': [4.6, 8.3, 9.0, 3.3, 1.8, 9.5, 2.2],
    'state': ['NY', 'TX', 'FL', 'AL', 'AK', 'TX', 'TX']
    }

index = ['Jane', 'Nick', 'Aaron', 'Penelope', 'Dean', 'Christina', 'Cornelia']

df = pd.DataFrame(data, index=index)

In [32]:
display(df["age"])
display(type(df["age"]))

Jane         30
Nick          2
Aaron        12
Penelope      4
Dean         32
Christina    33
Cornelia     69
Name: age, dtype: int64

pandas.core.series.Series

In [33]:
display(df[["color", "age"]])
display(type(df[["color", "age"]]))

           color  age
Jane        blue   30
Nick       green    2
Aaron        red   12
Penelope   white    4
Dean        gray   32
Christina  black   33
Cornelia     red   69

pandas.core.frame.DataFrame

In [31]:
display(df[["age"]])
display(type(df[["age"]]))

           age
Jane        30
Nick         2
Aaron       12
Penelope     4
Dean        32
Christina   33
Cornelia    69

pandas.core.frame.DataFrame

## .loc[]

`loc` is label-based data selection method which means that we have to pass the name of the row or column which we want to select. This method includes the last element of the range passed in it, unlike iloc. Along with that, it also uses the label names in the index.

In [36]:
# select all rows for a specific column
display(df.loc[:'Aaron', 'color'])

# Select all rows for multiple columns
display(df.loc[:, ['age', 'color']])

# Select multiple columns with specific rows
display(df.loc[['Jane', 'Nick'], ['age', 'color']])

# Select a range of rows for all columns
display(df.loc['Nick':'Dean'])

Jane      blue
Nick     green
Aaron      red
Name: color, dtype: object

           age  color
Jane        30   blue
Nick         2  green
Aaron       12    red
Penelope     4  white
Dean        32   gray
Christina   33  black
Cornelia    69    red

      age  color
Jane   30   blue
Nick    2  green

          age  color    food  height  score state
Nick        2  green    Lamb      70    8.3    TX
Aaron      12    red   Mango     120    9.0    FL
Penelope    4  white   Apple      80    3.3    AL
Dean       32   gray  Cheese     180    1.8    AK

## .iloc[]

On the other hand, `iloc` is an integer index-based method which means that we have to pass integer index in the method to select specific row/column. This method does not include the last element of the range passed in it unlike loc.

In [37]:
# select all rows for a specific column
display(df.iloc[:3 , 1])

# Select all rows for multiple columns
display(df.iloc[:, [0, 1]])

# Select multiple columns with specific rows
display(df.iloc[[0, 1], [0, 1]])

# Select a range of rows for all columns
display(df.iloc[1:4])

Jane      blue
Nick     green
Aaron      red
Name: color, dtype: object

           age  color
Jane        30   blue
Nick         2  green
Aaron       12    red
Penelope     4  white
Dean        32   gray
Christina   33  black
Cornelia    69    red

      age  color
Jane   30   blue
Nick    2  green

          age  color   food  height  score state
Nick        2  green   Lamb      70    8.3    TX
Aaron      12    red  Mango     120    9.0    FL
Penelope    4  white  Apple      80    3.3    AL

### Differences between .loc and .iloc

- `loc` gets rows (or columns) with particular labels from the index.
- `iloc` gets rows (or columns) at particular positions in the index (so it only takes integers).  
  
So `loc` is label-based data selecting method which means that we have to pass the name of the row or column which we want to select. This method includes the last element of the range. Unlike `loc`, in `iloc`, we have to pass the integer index in the method to select specific row/column. This method does not include the last element of the range.

### Working with Indexes: `set_index` and `reset_index`

By default, Pandas gives each row an integer index: `0, 1, 2, ...`.

We can choose a **more meaningful index**, for example an `id` column:

```python
df = df.set_index("id")
```
Benefits:

- We can select rows by meaningful labels using .loc.

- Some operations (like joins or time series) become more natural.

After some operations (for example, groupby), the grouping column(s) may become the index.
We can bring them back as normal columns with:
```python
df = df.reset_index()
```

In [46]:
idx_df = pd.DataFrame({
    "id":   [101, 102, 103, 104],
    "name": ["Alice", "Bob", "Charlie", "Diana"],
    "age":  [25, 35, 40, 19]
})

idx_df

    id     name  age
0  101    Alice   25
1  102      Bob   35
2  103  Charlie   40
3  104    Diana   19

In [47]:
# Set 'id' as the index
idx_df_indexed = idx_df.set_index("id")
idx_df_indexed

        name  age
id
101    Alice   25
102      Bob   35
103  Charlie   40
104    Diana   19

In [48]:
# Now we can use .loc with 'id' values
idx_df_indexed.loc[101]

name    Alice
age        25
Name: 101, dtype: object

In [49]:
# A simple groupby example where the group key becomes the index
grouped = idx_df.groupby("age").size()
grouped

age
19    1
25    1
35    1
40    1
dtype: int64

In [50]:
# Reset index to turn the index back into a column
grouped_reset = grouped.reset_index(name="count")
grouped_reset

   age  count
0   19      1
1   25      1
2   35      1
3   40      1

## Pandas Axis Manipulation

### Axis 0 and Axis 1
In pandas, `axis=0` represents rows (running vertically downwards across rows) and `axis=1` represents columns (running horizontally from left to right across columns).

Always remember, `axis=0` will act on all the **ROWS** in each **COLUMN**, `axis=1` will act on all the **COLUMNS** in each **ROW**. This becomes very important when you want to add rows, delete rows, or apply some calculation down a column or across a row.

In [45]:
df.loc[:,["age", "height"]]

           age  height
Jane        30     165
Nick         2      70
Aaron       12     120
Penelope     4      80
Dean        32     180
Christina   33     172
Cornelia    69     150

In [42]:
df.loc[:,["age", "height"]].sum(axis=0)

age       182
height    937
dtype: int64

In [43]:
df.loc[:,["age", "height"]].sum(axis=1)

Jane         195
Nick          72
Aaron        132
Penelope      84
Dean         212
Christina    205
Cornelia     219
dtype: int64

## Reading and Writing Data
Pandas provides functions for reading and writing data in a variety of formats. You can read data from a CSV file and write it to an Excel file, for example:

In [ ]:
# Read data from a CSV file
df = pd.read_csv('data.csv')
# Write data to an Excel file
df.to_excel('data.xlsx', index=False)

df_from_xlsx = pd.read_excel("data.xlsx")

In [55]:
df.head()

          age  color    food  height  score state
Jane       30   blue   Steak     165    4.6    NY
Nick        2  green    Lamb      70    8.3    TX
Aaron      12    red   Mango     120    9.0    FL
Penelope    4  white   Apple      80    3.3    AL
Dean       32   gray  Cheese     180    1.8    AK

In [61]:
df = df.reset_index(names="names")

In [62]:
df.to_csv("output.csv", index=False)

**Best practices**

In [72]:
import numpy as np

In [74]:
csv_example = pd.read_csv("output.csv", usecols=["age", "score"], dtype={"age":np.int32, "score":np.float32})

In [75]:
csv_example.head()

   age  score
0   30    4.6
1    2    8.3
2   12    9.0
3    4    3.3
4   32    1.8

In [66]:
csv_example.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     7 non-null      int64
 1   score   7 non-null      float64
dtypes: float64(1), int64(1)
memory usage: 244.0 bytes

In [76]:
csv_example.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     7 non-null      int32
 1   score   7 non-null      float32
dtypes: float32(1), int32(1)
memory usage: 188.0 bytes

### Reading/Writing JSON and Parquet

Besides CSV and Excel, modern data pipelines frequently use:

- **JSON**: semi-structured data, APIs, logs.
- **Parquet**: columnar format, efficient for analytics and big data tools (Spark, etc.).

Pandas can read and write these formats as well:

```python
# JSON
df = pd.read_json("data.json")
df.to_json("output.json", orient="records", lines=True)

# Parquet
df = pd.read_parquet("data.parquet")
df.to_parquet("output.parquet")
```
> Note: To work with Parquet you may need extra libraries installed, such as pyarrow or fastparquet.

In [ ]:
# Example: reading JSON (adjust the file path to your case)
# json_df = pd.read_json("data/example.json")
# display(json_df.head())

# Example: writing to JSON
# json_df.to_json("data/example_output.json", orient="records", lines=True)

# Example: reading Parquet (requires pyarrow or fastparquet)
# parquet_df = pd.read_parquet("data/example.parquet")
# display(parquet_df.head())

# Example: writing to Parquet
# parquet_df.to_parquet("data/example_output.parquet")

## Memory usage
Pandas provides functionality to explicitly check the memory usage of a DataFrame.

In [77]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   names   7 non-null      object
 1   age     7 non-null      int64
 2   color   7 non-null      object
 3   food    7 non-null      object
 4   height  7 non-null      int64
 5   score   7 non-null      float64
 6   state   7 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 1.8 KB

Here, `deep` provides the most accurate report of the memory usage, accounting for the true memory usage of all components of the DataFrame.

However, the memory consumption of a DataFrame is not only determined by the number of items but also the data type of the items. For instance, the data type `int64` consumes more memory than `int8`.

In [ ]:
# Perform operation to reduce memory usage
df['column_name'] = df['column_name'].astype('int8')

## Dealing with Large Datasets
You'll likely encounter datasets that are too large to fit into memory. In such cases, Pandas provides several techniques to handle this scenario:

- Chunking: Read data in chunks small enough to fit into memory.

In [ ]:
chunksize = 10 ** 6  # Tune this value to best match your memory availability
for chunk in pd.read_csv("large_dataset.csv", chunksize=chunksize):
    process(chunk)  # define a function to process your data

- DTypes: Minimize memory usage by specifying or converting data types.

In [ ]:
df = pd.read_csv('data.csv', dtype={'column1': 'int8', 'column2': 'float32'})

### Categorical Data Type for Repeated Strings

Many real-world datasets have columns with **repeated string values** and **few unique categories**, for example:

- `"region"`: `"North"`, `"South"`, `"East"`, `"West"`
- `"gender"`: `"F"`, `"M"`
- `"status"`: `"active"`, `"inactive"`

For these columns, Pandas provides the **`category`** dtype:

- Internally stores values as **integer codes** plus a small lookup table.
- Can reduce **memory usage**.
- Can improve performance for operations like `groupby` and `value_counts`.

We convert a column to `category` with:
```python
df["region"] = df["region"].astype("category")

Use `category` when:

- The column is text (object dtype).
- The number of unique values is small compared to the number of rows.

In [ ]:
cat_df = pd.DataFrame({
    "region": ["North", "South", "North", "East", "South", "West", "North", "East"],
    "sales":  [100, 200, 150, 130, 220, 90, 170, 160]
})

print("Before converting to category:")
print(cat_df.info(memory_usage="deep"), "\n")

# Convert region to category
cat_df["region"] = cat_df["region"].astype("category")

print("After converting to category:")
print(cat_df.info(memory_usage="deep"))

# Exploratory Data Analysis

Exploratory data analysis is an important step in understanding the data.

In [ ]:
# Get the summary statistics of the DataFrame
df.describe()

# Get the unique values in a column
df['colum_name'].unique()

## Descriptive Statistics with Pandas

### Mean, median, mode

In [ ]:
# create a pandas series
data = pd.Series(np.random.randint(low=0, high=10, size=20))

# calculate mean, median, and mode
mean = data.mean()
median = data.median()
mode = data.mode()[0]

print("Mean:", mean)
print("Median:", median)
print("Mode:", mode)

### Variance and standard deviation

In [ ]:
# calculate variance and standard deviation
variance = data.var()
std_deviation = data.std()

print("Variance:", variance)
print("Standard deviation:", std_deviation)

### Skewness and kurtosis

In [ ]:
skewness = data.skew()
kurtosis = data.kurtosis()

print("Skewness:", skewness)
print("Kurtosis:", kurtosis)

### Correlation
Pairwise correlation of columns: Exclude NA/null values when computing correlation.

In [ ]:
# create two pandas series
x = pd.Series(np.random.randint(low=0, high=10, size=20))
y = pd.Series(np.random.randint(low=0, high=10, size=20))

# calculate correlation
correlation = x.corr(y)

print("Correlation:", correlation)

### Counting values
Value counts: Compute a histogram of a 1D array (Series).

In [ ]:
# create a pandas dataframe
df = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Ella', 'Frank'],
    'age': [20, 25, 30, 35, 40, 45],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M']
})

# count values in a column
gender_counts = df['gender'].value_counts()

print(gender_counts)

Quantile-based discretization function: Divide data into equal-sized buckets.

In [ ]:
# create a pandas series
data = pd.Series(np.random.randint(low=0, high=10, size=20))

print(pd.qcut(data, 4))  # Quartile cut

# Next Material

Topics we are covering on next material:

* **Data cleaning and preparation** are essential steps in data analysis. Pandas provides functions for handling missing data, removing duplicates, and converting data types.

* **Data aggregation and grouping** involve summarizing data based on one or more variables. Pandas provides a groupby function for grouping data by one or more columns and performing various operations on the resulting groups.

* **Merging and joining data** involve combining data from different sources into a single dataset. Pandas provides functions for merging and joining data based on common columns or indices.

* **Time series analysis** is a specialized area of data analysis that deals with data that is indexed by time. Pandas provides functions for working with time series data, such as resampling, rolling, and shifting.

* **Reshaping and pivoting data** involve transforming data from one format to another. Pandas provides functions for pivoting and reshaping data, such as melt, pivot, stack, and unstack.

> Content created by [**Carlos Cruz-Maldonado**](https://www.linkedin.com/in/carloscruzmaldonado/).  
> I am available to answer any questions or provide further assistance.   
> Feel free to reach out to me at any time.